name: Betanet Spec-Compliance Linter
on:
  workflow_dispatch:
    inputs:
      binary-path:
        description: Path to the candidate binary
        required: true
        default: test-betanet.py

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run linter
        run: |
          python .\betanet-linter.py --binary "${{ github.event.inputs.binary-path }}" --format json --sbom

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: betanet-linter-artifacts
          if-no-files-found: error
          path: |
            report.json
            sbom.json
